### ISSUE TITLE
I get loads of errors when trying to play some YouTube videos

### ISSUE THREAD

**Issue by Qwerty-Space** [Just-Some-Bots/MusicBot#1029]
From what I gather in the command window, it doesn't like the URL, I think it contains characters it doesn't expect.

I can send the errors in PM

**Comment by bradleyNL** [comment]
can you pm me it is is very anoying

**Comment by arunesh90** [comment]
post the errors here so multiple people can check what's the problem.

**Comment by Qwerty-Space** [comment]
Update the dependencies.  There's an executable for it in the folder

**Comment by siemandelc** [comment]
How do you update for ubtuntu, @Qwerty-Space? sudo apt-get update and sudo apt-get upgrade?

**Comment by RubenBeeftink** [comment]
There's a file named update_macdeps.command. Just run that by typing 'sudo ./update_macdeps.command', it also works on ubuntu.

**Comment by fouadhammad1229** [comment]
@RubenBeeftink how do we run that in windows?

**Comment by RubenBeeftink** [comment]
@T0m0ko like @Qwerty-Space said, there should be an executable or .bat file in the folder to do that.

**Comment by jayktaylor** [comment]
As this issue seems to be taken over by people having a more recent issue, I'm going to close it. @Qwerty-Space if you are still having troubles please comment with a full error/stacktrace and we'll reopen this issue.

(To those having the more recent issue caused by youtube-dl, see https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717)

**Comment by Qwerty-Space** [comment]
I found the answer on the Discord server
