### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by afonsojramos** [Just-Some-Bots/MusicBot#1071]
```
\musicbot\bot.py:459: DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game)
```
I still get this warning after so much time, and sometimes the bot crashes due to this. Is there a fix?

**Comment by EndenDragon** [comment]
Crashing because of this is not a plausible cause. It is just sending this message saying that a code that MusicBot is using is outdated. You can safely disregard any `DeprecationWarning` messages and leave it to the bot maintainers to handle this issue. Actually, there has been proposed fixes (#684) that uses the new `change_status` method instead. Just wait for the new update for the new code.
