### ISSUE TITLE
Use Google API for YouTube

### ISSUE THREAD

**Issue by daimaah** [Just-Some-Bots/MusicBot#109]
Running MusicBot on some servers is very difficult you don't know how to force ipv4 or use a VPN etc. Another bot has solved this issue by using Google / YouTube API for YouTube access. This way the bot won't encounter captchas. This problem is constantly seen on OVH servers.

**Comment by srhinos** [comment]
We have implemented forced ipv4 in review but doubt we'll ever use any official API especially the official youtube API. We're able to broaden our compatible sites to well over a few hundred using youtube-dl rather than using the official API along with the fact that you can't download or stream with the official API so we'd be using youtube-dl either way.
