### ISSUE TITLE
The bot won't play anything anymore and spits out this error.

### ISSUE THREAD

**Issue by fashwink** [Just-Some-Bots/MusicBot#1094]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\DefinitelyNotMax\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1064, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\DefinitelyNotMax\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 952, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

**Comment by StarFscker** [comment]
Can confirm, same issue on mine as of a couple hours ago. 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'",))

So this is not a platform-specific error. I'm guessing it's a problem with the upstream youtube_dl, which is separate I think (right?)

While I'm waiting for an official response, I'm going to try checking out youtube_dl and seeing if there is anything that they're doing in regards to this.

**Comment by StarFscker** [comment]
I fixed it for myself. As I suspected, it has to do with an outdated youtube-dl. 

Update youtube-dl that on your platform, and restart the bot, and it should be perfectly fine. I do not know why I needed to restart but I did for some reason. 

http://rg3.github.io/youtube-dl/download.html

**Comment by fashwink** [comment]
@StarFscker I suspected as much, I was just unsure/had no idea how to update it. Thank you.

**Comment by koszmar3k** [comment]
@StarFscker Sorry but I'm not very experienced. Could you tell me in more detail what I need to do to exchange/update the youtube-dl file. I tried looking for it in the bots repository but had no luck however I could see pieces of code referencing this file. I would appreciate your help.

**Comment by R4to0** [comment]
Easiest way to update youtube-dl

`# /path/to/your/pip install --upgrade youtube_dl`

**Comment by jayktaylor** [comment]
Please check the [closed issues](https://github.com/Just-Some-Bots/MusicBot/issues?q=is%3Aissue+is%3Aclosed) before posting in the future. (https://github.com/Just-Some-Bots/MusicBot/issues/1072#issuecomment-297976717)
