### ISSUE TITLE
Can I translate the bot?

### ISSUE THREAD

**Issue by PlayRed** [Just-Some-Bots/MusicBot#115]
I want to translate the bot in german :D

**Comment by krlox91** [comment]
Same here but I'd like to translate to Spanish

**Comment by XCanG** [comment]
I think possible add in options.txt language switching and use something looks like **lang.en.txt, lang.de.txt, lang.sp.txt** e.t.c.
I also think about it and may be added this soon, if I can.

**Comment by XCanG** [comment]
@PlayRed @krlox91 added multilanguage support (90% now), you can see it in [my repository](https://github.com/JumpJets/MusicBot) and use it if you want.
P.S. If you help me translate text to other languages ([this file](https://github.com/JumpJets/MusicBot/blob/develop/config/lang.txt#L207)), I will be happy, because I really know only english and russian.
P.S.S. In **options.txt** you need setup **ServerLanguageMode** to use default language. Per user you need send `!setlanguage en/ru/de/es/sp/...` or `!sl ...`(shortcut). `!unsetlanguage` delete you personal settings in database.

**Comment by jayktaylor** [comment]
https://github.com/Just-Some-Bots/MusicBot/commit/ea5798669407d9e1e74b3bc8158f6a0e162b3c1b

**Comment by lmmfranco** [comment]
@jaydenkieran Nice to see yo guys are working on localization. Any updates on this?

**Comment by MattBSG** [comment]
@lmmfranco 

Hi, full localization support is complete for the most part. All response text is able to be translated (review branch), the only thing missing is command translations. If you copy the i18n en.json template and save a new copy of it (ie `es.json` for Spanish) you can see specify the language go use. If you’d like to PR a new language as well go ahead.

**Comment by lmmfranco** [comment]
Thanks @MattBSG.
Had some issues using the feature but ended up sorting it out.
Just opened a PR fixing the bug I found:
https://github.com/Just-Some-Bots/MusicBot/pull/1510

**Comment by MattBSG** [comment]
@lmmfranco Thanks! We’ll take a look
