### ISSUE TITLE
Then what is

### ISSUE THREAD

**Issue by Zoltus** [Just-Some-Bots/MusicBot#1157]
jhgg commented 7 hours ago
This repo is not the place to appeal bans.

Yes but there is no any other way? So unprofessional Staff and coders. Banned for no reason And impossible to appeal, Your staff team members are probably like 14 years old kids

WHERE DO I APPEAL???

**Comment by rafaelwastaken** [comment]
Obviously not on here, so posting again won't help lol

Also, I don't think that insulting the staff in semi-broken English will hep your case much

**Comment by Zoltus** [comment]
Well if staff member bans for no reason = Unprofessional, also i cant report staff members here then where?, So if Staff abuses his powers = nothing cant be done ? If thats the case it means owner is very stupid.

**Comment by junhui-f** [comment]
**Github**
> GitHub is a **development platform** inspired by the way you work. From open source to business, you can host and review code, manage projects ...

**Comment by jayktaylor** [comment]
Hello,

For a start, our [volunteer] staff team are not 14 year old kids, they are probably a lot more professional than you - for example, the person that closed your previous issue (#1156) is a developer @ Discord. I echo the statement that Jake said - this is not a place to appeal bans. This is a place for reporting issues relating to the MusicBot.

It isn't a privilege to have access to our help server. We help people in our own time. If we feel you're being a nuisance or causing problems, we will remove your ability to be on the server (which doesn't actually change much - if you have an issue with the bot, you can still post it here, your response just won't be real-time).

Even if we were willing to consider your ban appeal, you have nothing that we can even identify you with. Your name on GitHub does not match anyone that is banned on the server, nor any of our audit logs. You spent so much time making a big case on the previous issue that you didn't even consider that we wouldn't have a clue in the world who you were.

Finally, I'm going to answer the numbered points you made on your previous issue:

1. _"I didn't ask anything"_: We don't know what you said. We don't know who you are.
2. _"I didn't have any issue"_: Okay. Not everyone on the server is expected to have issues.
3. _"I didn't have any suggestions"_: See 2.
4. _"So that rule does not apply"_: Well it does. It states not to mention staff on the server.
5. _"If that was a rule, It means if somebody sends a staff member any private message = ban, Even if its not bot related, even if you tell him happy birthday."_: If your message is unwarranted, we don't want to receive it. If you have a genuine reason for messaging us rather than being a nuisance, sure. If you require help, we'll just point you to the server.
6. _"Why would everyone have rights to @ mention if its against the rules?"_: It is not possible to prevent people from mentioning other users. It is only possible to prevent using @ everyone.
7. _"I mentioned staff by accident because i have quote plugin in my discord. So for that shoudnt anyways get banned."_: So in this statement you basically admit to breaking the rule that you said doesn't apply to you. You're in control of the plugins you use. Plugins aren't even an official part of the client - so you're even more so responsible.

I'd also like to point out that you say _"I got screenshorts from chat except from the last message before ban."_ Okay, so where are they? You include nothing in your "appeal" that would actually help us do anything.

If you'd like me to review your ban, feel free to reply to this issue with identifiable information about your Discord account (like a username and discriminator) so I can see what actually happened. Please don't be hostile to people that take time out of their day to help other people with an open-source bot.

_**Edit: If you don't reply to this issue with information within 48 hours, I'm going to close it. This repo, as you were told, is not for these issues.**_

~ Jayden

**Comment by jayktaylor** [comment]
Hi. We found logs relating to you. Sorry for the incovenience, but its a little difficult to find someone when their Discord name is Z̝̩͍ͩO͕ͦḶ̺̜ͧT͓̜ͨU̠͍ͪṢ̺͓̜ͤ―็็๎็#9675.

You joined the server at 10:23 UTC on 16th May, and left about an hour and 20 minutes later. You rejoined at 13:25. At 15:44, your nickname was changed so that it was easily readable and mentionable in comparison to the zalgo text your username was/is. You left again at 17:16 after [complaining](http://i.imgur.com/xFavp6o.png) about the lack of help (again, we help voluntarily.), I believe you were **kicked** for mentioning staff, though I can't check this right now. You rejoined two minutes later.

For a while afterwards, you complained about the "abuse of power" of our staff. You complained that your name was changed. You were banned from the server at 20:39 after making a number of incorrect comments, exhibiting backseat moderation (both of which I've highlighted below), and generally being a nuisance.

![Image](http://i.imgur.com/ZZOvXkU.png)

As a result of this, we believe you were banned fairly. We don't have time to deal with people who are argumentative and causing problems - we're a help server for our bots. If you have a MusicBot related issue at any point, [feel free to leave an issue](https://github.com/Just-Some-Bots/MusicBot/issues/new).
