### ISSUE TITLE
Issue when updating the bot.

### ISSUE THREAD

**Issue by IceViper04** [Just-Some-Bots/MusicBot#1260]
I've tried multiple times to update my bot but when I write the command git pull in git bash it says that everything is already up to date but I don't have the new stream command or any of the new features yet. can someone help me with updating my bot so I can use all the new features? And yes I downloaded the bot after the instructions on this website.

**Comment by MeepCastana** [comment]
Those features are not available in the default version of the bot. Use review branch if you want the new commands

**Comment by chuushi** [comment]
Use the review branch by checking it out.

```
git checkout review
```

You can also checkout all the PR to try out those features as well.

**Comment by IceViper04** [comment]
The GitBash tells me this 

config/autoplaylist.txt
Please commit your changes or stash them before you switch branches.
Aborting 


Why does it do this? @SimonOrJ

**Comment by chuushi** [comment]
It's because your autoplaylist.txt is modified.  When you checkout branches, all modified files (except new files such as options.ini) will be reset.

**Back up** your `autoplaylist.txt` first, [hard-reset the repository](https://stackoverflow.com/questions/5807137/how-to-revert-uncommitted-changes-including-files-and-folders), then checkout the review branch.

```
git reset --hard
```

After resetting, copy your backed up `autoplaylist.txt` back into the project.

**Comment by IceViper04** [comment]
it keeps telling me this Unlink of file 'ffmpeg.exe' failed. Should I try again? (y/n)
And I have tried typing y but the same thing keeps popping up

**Comment by MeepCastana** [comment]
https://github.com/Just-Some-Bots/MusicBot/tree/review go here and download it. its the review branch. After you downloaded it repeat the same steps you did when you installed the normal version
