### ISSUE TITLE
review branch need help

### ISSUE THREAD

**Issue by loobing** [Just-Some-Bots/MusicBot#1364]
does anyone know where i can download the review branch with all the commands that is working something like this https://github.com/tzhongyan/MusicBot/tree/review

**Comment by tzhongyan** [comment]
That is the same review branch as upstream review branch, I was trying to merge it into master because I launched the bot in master branch and added some feature before I fully understand how git works. On hindsight, **DO NOT ATTEMPT WHAT I DID** as it was and it still is a mess.

So if you want to use the review branch from the repo, I think `git checkout review` is the command you are looking for.
