### ISSUE TITLE
blacklist and remove songs from autoplay list?

### ISSUE THREAD

**Issue by CuddleBear92** [Just-Some-Bots/MusicBot#140]
we should have a command that removes the song playing from the autoplay list aswell as blacklisting it, either in two commands or in one higher command for the mods of the bot. 

having a autoplaylist with 18k songs in it is really nice as things are always random, but at times i find files that isnt music and so on that got imported by a fault.

ofc this is my fault, but the way the autolist works with just text and links makes it super hard to figure those after the fact.

we need a quick way to remove things from the auto playlist.
note that this command should also auto skip when issued IMO. or atleast have an option for it. 
adding it to the blacklist would also make it so that noone can play that file again.

**Comment by imayhaveborkedit** [comment]
When I write the local playlists stuff, better playlist controls will be added as well.  The autoplaylist will be converted to this kind of playlist, and will probably have some sort of `!drop` command that will remove a song from the playlist.

**Comment by CuddleBear92** [comment]
thanks! <3

**Comment by BabyBoySnow** [comment]
This is ancient but there is now an autoplaylist command to help manage it

**Comment by itsTheFae** [comment]
For the record, the I think I have implemented *most* of the parts required for this feature.   
So items in the playlists should get pruned when they are played if they match something on the block list.  And when blocking new items it will attempt to remove exact matches from the selected playlist.   

There are probably still some bits that could be improved, but I'm just guessing since I haven't really made use of the feature myself.
