### ISSUE TITLE
Bot Leaves channel as soon as it just join. 

### ISSUE THREAD

**Issue by zweiex** [Just-Some-Bots/MusicBot#1433]
I've been using the music bot for ages and it never happened before. Just today when i tried to get it up, it suddenly has this problem. Any advice ? Thank You

**Comment by FoxAndRoses** [comment]
Re-install the bot, it's happening to everyone currently

**Comment by iBionix** [comment]
I had the same problem and redid the music bot and it's still doing the same thing. What should I do?

**Comment by Esp10n** [comment]
So is this a problem with everyone I have the same issue. Just keeps attempting to connect but doesn't go through.

**Comment by RCambier** [comment]
Updating dependencies (as for most cases) solved it for me. 
(Windows - Open update_deps.bat
Linux - In your console, run python3.5 -m pip install --upgrade -r requirements.txt
Mac - Open update_macdeps.command in Terminal)

**Comment by Oden-Allfader** [comment]
Updating dependencies did not do it for me, I'm afraid.

**Comment by ghost** [comment]
Same issue. Updating dependencies did not do it for me either

**Comment by Sieabah** [comment]
Tried to update my dependencies as well and was unable to get it to work. I wonder what changed that caused this issue?

**Comment by Sieabah** [comment]
Okay, I managed to get it to work by updating the dependencies as well as doing a git pull to update all files. Works fine now.

**Comment by k-e-keith** [comment]
Updating dependencies hasn't helped; the command line returns "Requirement already up-to-date" for each file.
How can one perform a git pull? I'm running the bot on Win 10.

**Comment by iDanny07** [comment]
Same issue here as well, whats the commands for pull and where do i execute?

**Comment by ghost** [comment]
If you didn't originally pull the repo then you can just click download again and replace the config files with yours. Mine works now

**Comment by JuppyPi** [comment]
Yeah can some one just give me a list of commands to run. Im running raspbian on a pi

**Comment by iDanny07** [comment]
Yea mine works now, I just downloaded the zip and put my config files back in there

**Comment by JuppyPi** [comment]
I replace the config files and it still doesn't work. It says this,"[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Ensuring we're in the right folder
[INFO] launcher: Checks passed.
[INFO] launcher: Moving old musicbot log
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "run.py", line 344, in main
    from musicbot import MusicBot
  File "/home/pi/Pon32/musicbot/__init__.py", line 74, in <module>
    from .bot import MusicBot
  File "/home/pi/Pon32/musicbot/bot.py", line 15, in <module>
    import colorlog
ImportError: No module named 'colorlog'
[INFO] launcher: Attempting to install dependencies..."


It then fails to install dependencies and suggests that I use sudo to install them. Im stupid and dont know how, can anyone help me out.

**Comment by iDanny07** [comment]
if you go into the script that you are executing try putting sudo at the beginning of the file.

**Comment by Sieabah** [comment]
@JuppyPi you need to reinstall the requirements.txt file it seems.

@iPhenix007 Adding sudo really shouldn't be your goto solution.

**Comment by iDanny07** [comment]
Agreed, but if he doesn't have permissions as the current user that would fix it. @Sieabah

**Comment by jayktaylor** [comment]
**To resolve this issue**, update to the latest version of the bot, and then update your dependencies, following the instructions on https://github.com/Just-Some-Bots/MusicBot/wiki/Updating. Simply running the dependencies update script is **not** enough.

---

### Regarding installing the bot

**Please** take the time to install the bot **properly** if you haven't already (e.g if you can't run `git pull` as noted on the link above). It will make your life updating the bot a lot easier. We **don't** provide support on our server or on GitHub for anyone that has downloaded the ZIP directly (it is obvious when we're helping you if you've done this).

---

If you **still** have issues after updating your bot, do the following:

- Verify that your bot has actually updated properly. When running it, it will say `Connected!  Musicbot v1.9.6` (note the version should be **1.9.6**, not 1.9.5_2 or earlier)
- Verify that your dependencies updated properly. When updating them, check for errors in the console.
- If you are still having issues, join our Discord server and ask for help. Please be patient in there, as people aren't around all day everyday, especially over the Christmas period: http://discord.gg/bots

I'm going to keep this issue open until the end of the year so that people with similar issues can hopefully spot it and find the solution.
