### ISSUE TITLE
My bot is able to join the channel but won't play music

### ISSUE THREAD

**Issue by RahmanNoodles1** [Just-Some-Bots/MusicBot#1448]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue
When I try to play music, it queues up the command but then the bot leaves the channel and rejoins and does not play anything

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

**Comment by jayktaylor** [comment]
You’ve said you’re using version 1.9.6_1 of the bot but you’re clearly not if you’re having this issue. You should also have looked at existing issues before creating a new one. 

The solution to your issue is on leaving: https://github.com/Just-Some-Bots/MusicBot/issues/1433#issuecomment-353684748.
