### ISSUE TITLE
Seems as if the bot has a dependency on latency.

### ISSUE THREAD

**Issue by Xemiru** [Just-Some-Bots/MusicBot#145]
I can't read Python, so I'm not exactly sure how much leverage you have over this, but I'd assume the bot would be able to notice whether or not its dying and just pause itself to resume when its stable. Whenever the bot starts lagging, obviously it starts stuttering, but the main issue of this submission is that the bot eventually shuts down (crashes) only while its lagging.

At least, that's what it looks like. I'm not using the bot myself, the bot's being used on another server and the owner does mention there're stacktraces that appear after the bot dies through the aforementioned scenario.

It only seems to not be able to play and broadcast to the voice channel, as it still accepts commands as noted by the entire server trying to save it by removing all songs from the queue and refilling it.

**Comment by imayhaveborkedit** [comment]
I can't do anything about your internet, and I tell you much without a stacktrace, but if there is one, and it mentions something about `a non-blocking socket operation could not be completed immediately`, that's a known issue that happens to people with poor internet.  It's also partially a library issue, since the discord.py author says he's going to have the bot drop packets when it happens, so the bot won't crash.
