### ISSUE TITLE
Editing the help command

### ISSUE THREAD

**Issue by 7ekhed** [Just-Some-Bots/MusicBot#1474]
When I do !help it links to a non existant github page. Is the help command editable?

**Comment by ImthePeach** [comment]
Please edit your initial post following our Issue Template here: https://github.com/Just-Some-Bots/MusicBot/blob/master/.github/ISSUE_TEMPLATE.md

Also when doing so please provide more explanation of your issue via screenshots or other means.

**Comment by MattBSG** [comment]
Hi, as Peach said please use the issue template in the future. This has been fixed in review with #77e9a75 so until it’s merged please use the new wiki link https://just-some-bots.github.io/MusicBot/

**Comment by 7ekhed** [comment]
What I was trying to say was, it brings up the help menu, but below it is a non-existent GitHub link. Is it possible to edit the file and change this?

**Comment by 7ekhed** [comment]
This isnt a bot being broken issue, I was just wondering if I could edit the help command, and where I could find it so I can edit it

**Comment by MattBSG** [comment]
I mean, it’s fixed in our review branch and will get pushed soon to master, but if you *really* want to change it still, `MusicBot/musicbot/bot.py` `cmd_help` function. You’ll have to change it back/force pull when we merge or you won’t be able to get it. As long as you’re fine with that and know we don’t give support for modifications, go ahead.
