### ISSUE TITLE
MusicBot instantly removes majority of songs from autoplaylist

### ISSUE THREAD

**Issue by k-e-keith** [Just-Some-Bots/MusicBot#1476]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [ x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x ] I am running version 1.9.6_1 of MusicBot

----

### Description of issue

The MusicBot is removing ~1,400 songs from the autoplaylist, all within seconds of one another, despite the songs being both fully accessible on YouTube and present in the audio_cache. 

I know from checking some of the other support threads that movement of songs to the autoplaylist_removed file is a feature by design, but I'm completely baffled as to what could be causing the *majority* of the files in the playlist to be moved so _quickly_. I mean, most of these are being dumped within the same minute of one another, if not the same second.
A dump of the autoplaylist_removed file with timestamps is viewable below (ctrl+f 20:48 and you'll surely see what I mean:)
https://pastebin.com/udT1gdBi
These other threads mention the possibility of a dropped connection causing the song removal, but I'm on a consistent wired connection and have no network troubles at all while using my computer. So I'm really at a loss, here.

Each file the bot removes is currently up and running via YouTube, and most of the files are also saved in the offline audio_cache. As such, I can't understand what's causing this issue. I'm on the latest updated build (git pulled just before writing this) and my dependencies are fully updated as well.

Does anybody have any clue what could be causing this to happen? 

### Steps to reproduce

1. Run MusicBot.
2. Observe changes to autoplaylist.txt and autoplaylist_removed.txt
3. ???

----

### Log file

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1649585/musicbot.log)

**Comment by k-e-keith** [comment]
Nothing?

**Comment by MattBSG** [comment]
To clearify how the bot works, I’ll say this; In the pastebin you linked those errors are exceptions. By design when an exception is thrown while attempting to download the song it is removed (in most cases this will be a privated or removed video). Now this can be triggered by other issues that surface such as [this](https://github.com/rg3/youtube-dl/issues/3201) or [this](https://github.com/rg3/youtube-dl/issues/8836) (same exception as you) which seem to directly correlate to connectivity issues temporary or not. I recommend updating your dependencies/bot and trying to run the bot on another computer in the same building to see if it’s your machine or internet (even if you can visit youtube.com normally it could break with embeds) if that doesn’t work. I really don’t have much more to offer you though since it’s a problem with the youtube-dl library, not musicbot (we use it to download audio).

**Comment by k-e-keith** [comment]
@MattBSG Thanks for clarifying, I appreciate it. I was baffled as to whether or not the issue was on my end. I'll take a more in-depth look into the issue if it re-arises, as I've gone without issue since initially posting.

**Comment by Munzy** [comment]
I've seen this as well.

**Comment by MattBSG** [comment]
Assuming since you never replied back if it kept happening that this is resolved. Feel free to ewopen if it arises again!
