### ISSUE TITLE
Please help, my music bot continues to restart itself in my Discord server

### ISSUE THREAD

**Issue by Babygirlsbigdaddy** [Just-Some-Bots/MusicBot#1478]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ x] I am running version 1.9.6_1 of MusicBot

----

### Description of issue

When ever the bot loads into the server it says its playing a song, and then resets. clearing out the playlist.

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.
 Unable to retrieve.

**Comment by jayktaylor** [comment]
Without a log file, we can't really help you.

**Comment by Babygirlsbigdaddy** [comment]
Do you know where I can find the log file? :/

**Comment by mLgz0rn** [comment]
Since you are running 1.9.6_1 I would suggest you to try and update to 19.6_2, it has a fix for youtube-dl.
And about your log file, it literally says where your log file is located when you create an issue.

> Log file
Please attach your MusicBot log file (located at logs/musicbot.log) to this issue. You can do so by dragging and dropping the file here.
