### ISSUE TITLE
Bot keeps playing in empty channel [Raspberry pi]

### ISSUE THREAD

**Issue by ThatzOriginal** [Just-Some-Bots/MusicBot#1482]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [X] I am running version 1.9.6_2 of MusicBot

----

### Description of issue

Bot doesn't auto pause when in an empty channel. (I also reinstalled rasbian and the bot onto the Pi just to make sure and issue still persisted)

### Steps to reproduce

1. Install the bot on a raspberry pi

2. Set in options pause when empty channel.

3. Join the channel with the bot in it.

4. Leave the channel (bot keeps playing with empty channel.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1658014/musicbot.log)

**Comment by itsTheFae** [comment]
This is due to the checking for empty channels (`VoiceStateUpdate`) being a little funky, as well as `on_player_finished_playing()` not setting up a check for empty channels when it queues a new song (like the check used in `_join_startup_channels()`)  

I've patched part of this issue but haven't added the checking to `on_player_finished_playing()` as I'm almost sure there is a better method than just copying the lambda used in `_join_startup_channels()` but I am not the person to make that call.  Keeps the patch work a tad more simple too.. 

Devs can find the related code in a cloned repo here:  https://github.com/itsTheFae/DiscordMusicBot/tree/patch-auto-pause

**Comment by MattBSG** [comment]
@itsTheFae Thanks for the work, if we’d like anything updated we can request changes in a PR. No harm in submitting one though :)

**Comment by jayktaylor** [comment]
#1484 should have fixed this.
