### ISSUE TITLE
Discord Bot playing songs not in autoplay list

### ISSUE THREAD

**Issue by Soulseller11** [Just-Some-Bots/MusicBot#1500]
- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_2 of MusicBot

----

### Description of issue
I recently set up a music bot in my discord and messed around with the settings a bit, with pldump etc. trying to make a custom playlist to play passively. But all of the songs in the autoplaylist, youtube links, are ignored. I went into the settings and turned off autoplaylist, but when i skip a song, it plays a random one, NOT in the autoplay list. I also tried to set it so after every song, it automatically deletes from my audio cache, but every song I !play and the autoplayed songs STAYS in the audio cache until I delete them manually.
Other than this, the bot works fine.

----

### Log file

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1693471/musicbot.log)

**Comment by MattBSG** [comment]
Hi, there is no reason I can see why the bot would play random songs not in the autoplaylist. Are you adding the songs to `_autoplaylist.txt`? That is a file used by the bot to move URLs that do not work. If you missed the underscore that could be why you were expecting songs in there to play but the default ones in the autoplaylist play. Please clear `autoplaylist.txt` entirely and replace with your music.

If you have `SaveVideos = yes` in your options.ini file and not prefixed with a `;` (meaning it is commented out) then the cache will be kept, otherwise they will only be kept to just play them. 

Also, a good rule of thumb with our bot until we solve some kinks is to use python3.5, not 3.6 (as you are using) which may cause other issues down the road as of now. Let me know how it goes.

**Comment by Soulseller11** [comment]
I completely replaced both of the autoplaylists but since restarting it, it wont even play the random songs anymore, only requests

**Comment by Soulseller11** [comment]
Update: it fixed itself after restarting my computer a few times, not sure why. But it's playing songs set-up in the autoplaylist now c: I put the semi-colon in front of my custom options, and so far they've worked as well, thanks for the help!
