### ISSUE TITLE
Restart breaks bot (windows)

### ISSUE THREAD

**Issue by Mudsaf** [Just-Some-Bots/MusicBot#1503]
Please make sure these boxes are checked (put an 'x' inside them) **before** creating the issue.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [x] I am running version 1.9.6_3 of MusicBot

----

### Description of issue

After restarting the bot, it wont rejoin to channel & stops working completely. No error messages given on "CMD" window of musicbot. Running with Windows OS, this worked before but somehow broke some months ago.

### Steps to reproduce

1. 

----

Don't know how to reproduce at your end, but for me i just downloaded via git new installation, moved my audio cache and did configs & this keeps happening.

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1714903/musicbot.log)

**Comment by AutumnClove** [comment]
The devs are aware of the restart command breaking. A fix is currently being worked on. In the meantime, you'll have to do runbot again. Sorry.

**Comment by robin840211** [comment]
Also have this issue with the same condition too, while following guide to install bot, and whatever py version above 3.5.x, updated dependencies much times. This problem has already exist after upgraded to 1.9.6_x since 1.9.5_x can restart normally (all 1.9.6_x now has the same problem).
I found that if directly double clicking to execute run.py, the bot's restart will working normally. The problem only occured if using batch file or manually running though cmd, which will stuck "once" in command prompt window after !restart (means if manually execute "exit" in cmd window, the bot will then always restarting normally with !restart command).
Another thing...all method will cause the py.exe dissapeared in Windows taskmanager after bot restarted, but python.exe still running. Is that normal.........?

Hope the info may help. :/ <- not good at programming
