### ISSUE TITLE
An error occurred when I run the bot

### ISSUE THREAD

**Issue by rikusen0335** [Just-Some-Bots/MusicBot#1512]
- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
-> I checked it with `python3 --version`.

- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script
- [ ] I am running version 1.9.6_3 of MusicBot
-> But I have updated dependencies with `update_dependencies_linux.sh`. I don't know version because I don't know how to know the version.

----

### Description of issue

Error occurring when I start the bot.
And I am using Ubuntu server 16.04.3.

### Steps to reproduce

1. Run the bot with `runbot_linux.sh`
2. Loading and checking something
3. An error occurs
----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1754101/musicbot.log)

**Comment by hs7982** [comment]
I have the same issue!

`discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..`

**Comment by MattBSG** [comment]
Hi everyone. This issue represents a situation where the bot is disconnected from Discord. This could be an internet issue on your part or Discord’s. Since a lot of these reports are coming at once (in our support server and here), it is more than likely this is an intermediate issue on Discord’s side which we cannot do anything about. I’m going to leave this issue open for a day so other people who may experience this do not open new issues.

**Comment by rikusen0335** [comment]
I don't think so. Because when I tried to change server region, then the bot working correctly.
(Japan -> Singapore)

**Comment by rikusen0335** [comment]
I'm sorry I just update the bot, then the bot running correctly!
