### ISSUE TITLE
Whitelist does not load?

### ISSUE THREAD

**Issue by jacobmix** [Just-Some-Bots/MusicBot#153]
Wishlist doesn't seem to work. I've added role ids, and user ids.
But i have to manually re-add them every time i restart the bot.

**Comment by arunesh90** [comment]
We can't see whats wrong withouth the permissions.ini

**Comment by jacobmix** [comment]
Here's my files https://drive.google.com/folderview?id=0B0WFA9YZKBygdWgzSHMwNmo4NnM&usp=sharing

Permissions works fine. It's just that with "WhiteListCheck = yes"
It seems to not load ids from "whitelist.txt"
Don't matter tho. I've just set WhiteListCheck to no,
and made the permissions for "Default" to only be "help" and "perms".

**Comment by SLY985** [comment]
So was this ever figured out? Because we are currently having this issue and I really don't want to have to find some work around to just disabling the use of whitelist. I wish the function of being able to just whitelist a specific role was implemented already but for now I'm fine with doing it the way I have to, just getting tired of constantly having to retype each user into the whitelist.

**Comment by imayhaveborkedit** [comment]
The old whitelist is basically superseded by permissions now.  I suggest you use that instead.  I'm not sure why the whitelist seems to be being overwritten though.

**Comment by imayhaveborkedit** [comment]
The whitelist has been removed.
