### ISSUE TITLE
Raspberry Pi 3B+ Errors

### ISSUE THREAD

**Issue by AceTheGmodGeek** [Just-Some-Bots/MusicBot#1565]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [x] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The installation works fine; besides the part where I can't install the 
`sudo add-apt-repository ppa:deadsnakes -y
sudo add-apt-repository ppa:mc3man/trusty-media -y
sudo add-apt-repository ppa:chris-lea/libsodium -y` part. After the complete installtion, the bot works; but the chat messages are duplicated, so when I pause something, it says my vote has been ackowledged... then it says in another message Error "Can't skip! The player is not playing." So, the message is doubled; the first one is successful, but the second one is an error.

### Steps to reproduce

1. Install the bot all the way and skip `sudo add-apt-repository ppa:deadsnakes -y
sudo add-apt-repository ppa:mc3man/trusty-media -y
sudo add-apt-repository ppa:chris-lea/libsodium -y`, then attempt to use any command, and it will be doubled. One is successful, and the second one is errored.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

https://pastebin.com/qvBBEAv9
I couldn't drag and drop the file here; it's on a different OS.

**Comment by AutumnClove** [comment]
I believe you have a double instance of your bot running.

**Comment by AceTheGmodGeek** [comment]
How would I disable one instance? I don't think I have two instances; when I restart the pi, the bot completely goes offline, which leads me to believe there is only one instance, unless I've done something wrong.

I don't mean to be rude by this, thank you so much for replying!

**Comment by AutumnClove** [comment]
You might have a pm2 running? I'm sad to say I don't really know linux very well.

**Comment by amit177** [comment]
Can you say why you can't install the repos?

**Comment by AceTheGmodGeek** [comment]
pm2? I'm running off Raspbian, which is based on Debian but more optimized

Originally, I had a problem with installing the repos, but someone else suggested just to skip the step, that worked. But I get the problem `pi@raspberrypi:~ $ sudo add-apt-repository ppa:deadsnakes -y
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/stretch
`

**Comment by amit177** [comment]
@jaydenkieran

**Comment by GeoZzNL** [comment]
I also had al lot of issues on my pi3. 
Download Python-3.6.1.tar.xz from https://www.python.org/

Unzip the file and keep the folder in home directory.

Open terminal in that directory and perform the following commands:
./configure
make
make test
sudo make install
This will install Python 3.6 but pip3 may not be working.Install necessary modules using:
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

Now write the following to re run the installation (EDIT: USE -j4 FOR ALL CORES, WHICH IS ACTUALLY JUST 50% CPU):
sudo make
sudo make install

Now this, even if its again... (If pip3 is not working try pip)
sudo pip3 install numpy
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

If not working, do not uninstall a thing but follow the ubuntu 16 guide.

Then try some of my codes again.

I do not have a really good guide because i tried installing the bot and it tooks more than 3 days. Some of these codes fixed it for me. Running 3 bots using python3.6

**Comment by XFlawless1** [comment]
@AceTheGmodGeek The same output came to me. When I tried to add the repository. Directly try installing the packages they are yet available.

**Comment by AceTheGmodGeek** [comment]
@XFlawless1 I just skipped that step, and the bot seems to be correctly working. So, I guess I'll just wait for it to break before I come back and try to get those repos to work.
