### ISSUE TITLE
No audio unless rejoin channel.

### ISSUE THREAD

**Issue by Esp10n** [Just-Some-Bots/MusicBot#1567]
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update_dependencies` script

Which version are you using?

- [X] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
 Users can't hear the Musicbot produce music unless they disconnect from the voice channel and enter again. Anyone experiencing this?

EDIT: Also happens with me have to rejoin the voice channel the musicbot is in to hear music.

### Steps to reproduce

1. Restart bot, summon bot to voice channel with users already in it play song only to notice that my friends can't hear it except me (I am the owner of the bot) ask them to rejoin to solve the problem.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1866407/musicbot.log)

**Comment by Jimgersnap** [comment]
I am experiencing the same issue. Most, if not all, users can hear the bot while one user cannot - seems to occur to the same few users every once in a while. The user disconnecting and reconnecting fixes the issue. The bot can also disconnect and reconnect to fix the issue. Not sure if this is a Discord server connection issue with the user or the bot. 

I've basically ignored the issue since it happens very occasionally.

**Comment by mwallis45** [comment]
If some can hear it and others not at the same time then its a discord problem. something similar to this is having the bot muted and then you come in and still hear it. That is a discord problem and we are unable to fix. If not then it can also be down to `pause if empty` in config.ini

**Comment by Jimgersnap** [comment]
I agree on it being a Discord issue. I came to the same conclusion. But, it's definitely not `pause if empty` since the bot is actively sending sound while one or two people cannot hear it. 

It also seems to be completely random. Sometimes it occurs when a user just joins and they can't hear the music already playing. Sometimes they've been in the channel for a while - someone queues a new song - and the single user cannot hear it. I haven't been able to tie to it any websocket disconnections/reconnections. It's a pretty rare event.
