### ISSUE TITLE
无法使用MusicBot，因为中国内陆无法访问国外网站

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#1604]
Please tick all applicable boxes.

- [-] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [-] The latest `master` version (1.9.7)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [-] Feature request
- [-] Question

----

### Description of issue

如果使用的是中国内陆的网络，则MusicBot完全不可用并报错（我是一个几乎没有经验使用GitHub的用户，所以我并不懂如何使用这些规则）
我可以给你们一个解决方案，这是我们中国内陆常用的音乐播放链接：
http://music.163.com/m/song?id=461347998
如果是通过分享得到的链接，则会成为：
http://music.163.com/m/song?id=461347998&userid=80323528
非常简单，但难点在，如果用户只搜索歌曲名，我想开发难度会变得非常大

### Steps to reproduce

1. 使用任何与网络无关的步骤
2. 连接VPN

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/1971709/musicbot.log)

- [ ]

**Comment by AleanaA** [comment]
这只是一个翻译使用谷歌翻译的人不能像我这样的中文，希望这个问题很快就会为你解决。

Translated: This is just a translation using Google Translate for people that can't read Chinese like me, Hopefully the issue gets resolved soon for you.

### Unable to use MusicBot because mainland China cannot access foreign websites

#### Description of issue
If you are using a Chinese mainland network, MusicBot is completely unavailable and incorrect (I'm a user with little experience using GitHub, so I don't know how to use these rules)
I can give you a solution, which is a commonly used music playback link in mainland China:
Http://music.163.com/m/song?id=461347998
If the link is obtained through sharing, it will become:
Http://music.163.com/m/song?id=461347998&userid=80323528
It's very simple, but difficult, if users only search for song titles, I think it will be very difficult to develop.

#### Steps to reproduce
1. Use any network-independent steps
2. VPN connection

**Comment by ImthePeach** [comment]
`!play song name` defaults to search youtube for the song. Since mainland China has since blocked youtube since 2009 this will not work for you. You will need to play URL's directly, or you can use the search method with the available search engines that are not youtube.

Your other option would be to use the bot on a VPS such as DigitalOcean that's set up somewhere not in China to use the YouTube feature. Sorry for the inconvenience.
