### ISSUE TITLE
Live Streaming support

### ISSUE THREAD

**Issue by benoxoft** [Just-Some-Bots/MusicBot#165]
Hi there,

I'm playing around with your bot to have support for live streaming.  So far, I found 2 approaches that could be explored further.  I tried both and they both work:
1. Create a new command like this: !stream http://website.com/livestream.mp3
   This new command could bypass youtube-dl and give the link directly to ffmpeg.  This only works with a radio stream, so no support for twitch.tv or the like.  However, this method could probably allows the bot to display the name of songs it is currently playing.
2. Make the download of a song with youtube-dl non-blocking

This approach is a bit more tricky because of the thread pool and the cache folder.  First of all, you don't need to wait for the file to be fully downloaded to start playing it.  You can start playing the temporary file right away and rename it when it's done without any problem because ffmpeg will still have the new renamed file open.  The problem arise when skipping, pausing or stopping the stream.  I didn't go that far yet but if we add code to kill the worker thread and delete the temporary file when it stops playing, we could have livestream support working I think.

What do you think?  I'm willing to do it on my own and submit a PR when I'm done if you're interested.  Fantastic piece of software by the way, we all love it!

Cheers!

**Comment by jayktaylor** [comment]
https://github.com/SexualRhinoceros/MusicBot/commit/728c4cdf1ac21c6229f05530ccd68a509311d9ff  and later commits to `review` have implemented streaming. It'll be in the next release version.

**Comment by deansheather** [comment]
This request is in a milestone in another issue: #264.

**Comment by TiagoFrancisco2160424** [comment]
Hi, 

So which is the command? !stream url?
Because I have those Radio's IP's: 

HiperFM: http://85.25.73.243:10460/
RFM: https://playerservices.streamtheworld.com/api/livestream-redirect/RFMAAC_SC
Mega Hits: http://19553.live.streamtheworld.com:80/MEGA_HITS_SC
+Kizomba: http://109.71.41.250:8123/
Orbital: http://195.23.85.126:8401

In those radios url's, just the RFM Station works. "!stream https://playerservices.streamtheworld.com/api/livestream-redirect/RFMAAC_SC"

Regards.
