### ISSUE TITLE
on_voice_state_update

### ISSUE THREAD

**Issue by Cuteminded** [Just-Some-Bots/MusicBot#1726]
Please tick all applicable boxes.

- [X ] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X ] The latest `master` version (1.9.8)
- [X ] The latest `review` version

What type of issue are you creating?

- [X ] Bug

----

### Description of issue
you get this every time you enter a voice channel and the bot does not play
[
[145.6870322227478027] 2018-09-11 23:25:57,672 - ERROR - musicbot.bot | In bot.py::MainThread(4652), line 901 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Quinn\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 221, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Quinn\Desktop\MusicBot\musicbot\bot.py", line 2796, in on_voice_state_update
    player = await self.get_player(channel)
  File "C:\Users\Quinn\Desktop\MusicBot\musicbot\bot.py", line 425, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use ~summon to summon it to your voice channel.
]

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2372788/musicbot.log)

**Comment by AleanaA** [comment]
In your log, just before that started happening, you seem to have run `~disconnect`, removing the bot from the voice channel. Summon the bot again, and the error should go away.

**Comment by Cuteminded** [comment]
https://www.youtube.com/watch?v=K6ZfOULCy-k

**Comment by rtrind** [comment]
Duplicate of #1697. And yes, summoning the bot stops the exception but does not make it right. It is still a bug (although minor) which needs to be looked at.

**Comment by hrtrd** [comment]
Same error. 

log https://pastebin.com/rbBUf4Y8   

deleted channel, create new voice channel for all users, without some premissions. Disconnected and summon bot, same error. And cant play
[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "C:\Users\Администратор.WIN-4DVJVBMI0NM\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 242, in _run_event
    await coro(*args, **kwargs)
  File "D:\music\MusicBot\musicbot\bot.py", line 2842, in on_voice_state_update
    player = await self.get_player(channel)
  File "D:\music\MusicBot\musicbot\bot.py", line 431, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use $summon to summon it to your voice channel.

**Comment by hrtrd** [comment]
> Duplicate of #1697. And yes, summoning the bot stops the exception but does not make it right. It is still a bug (although minor) which needs to be looked at.

[ERROR:bot] Exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "/home/neoll/MusicBot/musicbot/bot.py", line 2844, in on_voice_state_update
    player = await self.get_player(channel)
  File "/home/neoll/MusicBot/musicbot/bot.py", line 431, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use $summon to summon it to your voice channel.

**Comment by ghost** [comment]
Sorry, i'll just add my issue to the comments below since i had issues with posting this before.


Hello, sorry for asking but i have some issues with the code for my MusicBot. I wanted to learn how to create custom commands for MusicBot so i tried creating a simple command of reply (basically the concept is if you write "hi" the bot should reply "Hi {user.name} !" ). Considering that i didn't know how to code with Python, i tried looking on the web and i was close to solving the issue myself. Until this showed up: [ERROR:bot] Exception in on_voice_state_update Traceback (most recent call last): File "C:\Users\User\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 255, in _run_event await coro(*args, **kwargs) File "C:\Users\User\Server\Bot\MusicBot\musicbot\bot.py", line 2846, in on_voice_state_update player = await self.get_player(channel) File "C:\Users\User\Server\Bot\MusicBot\musicbot\bot.py", line 431, in get_player 'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix) musicbot.exceptions.CommandError: The bot is not in a voice channel. Use !summon to summon it to your voice channel. Now for the bot to start normally again i should just delete the part that i wrote, but i want this to work since i could learn how to create commands. If someone had the same issue, please feel free to repost your situation below in the comments. Anyway, if someone could help me that would be really helpfull. Thanks for reading so far (i know, it's a lot). Atlas

**Comment by AutumnClove** [comment]
@AtlasSurfin 
The error has nothing to do with your code, however we don't help with modifications.

**Comment by ghost** [comment]
I... see. Still thanks for answering me in such a short time. Have a nice day.

**Comment by AutumnClove** [comment]
If you git checkout review or git pull if you're already on it, I believe it should be fixed.

**Comment by AutumnClove** [comment]
This should be fixed in review now.
