### ISSUE TITLE
You don't have permission to use that command.

### ISSUE THREAD

**Issue by qYuki** [Just-Some-Bots/MusicBot#1798]
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [x] Question

----

### Description of issue

> Error
You don't have permission to use that command.
Reason: You do not have permission to play media from this service

### Steps to reproduce

1. the play command (default: !play)

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2670733/musicbot.log)

**Comment by TheerapakG** [comment]
In the latest release of the bot, I made a PR that intend to give owner more control over their perms by having  'Owner (auto)' section. Some command in the prior version of the bot checks if you're owner along with perms instead which some owners seem to feel unfair. If in perms file you don't have 'Owner (auto)' section it will fallback to default non-permissive perms in the current release (assuming user want old behavior) which is what the bot do in prior version according to perms command in earlier version (This seems to confuse many people so next release (If my PR, #1794, got merged) owner will always get the power of permissive perms when bot can't find 'Owner (auto)' section). Since the command that checks ownership along with perms doesn't check for ownership now you get the permission error. For now, just copy over 'Owner (auto)' section from the example permission file and you will get permissive perms.

Note: I introduced a bug  (╯°□°)╯.  Set InstaSkip/ Remove and other Boolean-based perms manually for now (Boolean-based permissive perms are bugged, other options don't get affected, it also get fixed in the same aforementioned PR).

**Comment by qYuki** [comment]
I copied the "Owner (auto)" line from permission file example to the permissions.ini but still the same with that error.

**Comment by TheerapakG** [comment]
What is the output of perms command?

**Comment by qYuki** [comment]
Never mind i found the problem.
Hint: the syntax for the bot when write 

> !play

 should warn the user to use an YouTube/Soundcloud link or if will not work.
That's why i got that error

> "Error
> You don't have permission to use that command.
> Reason: You do not have permission to play media from this service"

I was confused about the command and forgot exist 

>!search "name of song/album"

for searching videos/songs on YouTube.
**Conclusion** 
Change the warning message from 

> "Error
> You don't have permission to use that command.
> Reason: You do not have permission to play media from this service"

**to**

>Error
>Syntax error: %s
>Reason: Should use an YouTube/Soundcloud link.

This is my opinion.

**Comment by AleanaA** [comment]
@qYuki That would be incorrect as the bot can play songs from services outside Youtube or Soundcloud.

**Comment by TheerapakG** [comment]
As previously asked, what is the output of perms command?

**Comment by qYuki** [comment]
@AleanA no one mentioned that case, and yes it will be incorrect. But still no one mentioned it here.

@TheerapakG i will upload the output later.
