### ISSUE TITLE
when i restart a host bot does not produce any sound

### ISSUE THREAD

**Issue by unwell35** [Just-Some-Bots/MusicBot#1905]
Hi , and sorry iam bad english
When I restart a "heroku" host I play a song but no sound is issued
Just changing playing bot to name song but the song does not work and does not produce any sound ..

If you want to record video to understand my problem more I have no problem

**Comment by AleanaA** [comment]
Unfortunately, we don't support hosts such as Heroku as issues like this can arise from using it.
This is generally due to the way voice works with discord, and Heroku just doesn't play nicely with it.
I'd recommend moving to a new host, or hosting it locally if an alternative host is not available to you.
