### ISSUE TITLE
[Feature request] Play audio from NetEase music

### ISSUE THREAD

**Issue by YuiyuD** [Just-Some-Bots/MusicBot#1914]
As the title, can we add feature play audio from NetEase, this is repo can do that, thank you guys so much!

https://github.com/xiaoxi654/discord-netease-music-bot

**Comment by TheerapakG** [comment]
Pretty sure youtube_dl have netease extractor already.

**Comment by YuiyuD** [comment]
so, just update youtube_dl and play the link like this: https://music.163.com/#/song?id=27713179
and we can play this audio, I just did not try yet

**Comment by Dayuan-mc** [comment]
the bot can't play audio from netease yet.

ERROR:No video formats found.

**Comment by TheerapakG** [comment]
It's YoutubeDL not being able to extract audio from the page.
relevant bits of code:
https://github.com/ytdl-org/youtube-dl/blob/3089bc748c0fe72a0361bce3f5e2fbab25175236/youtube_dl/YoutubeDL.py#L1523
For me when I go to that page I can't play it because "Due to copyright protection, your area is temporarily unavailable." or at least that's what Google Translate told me which would describe why YoutubeDL not able to download it.

**Comment by Dayuan-mc** [comment]
fine.thanks.

**Comment by YuiyuD** [comment]
true, NetEase block outside China region, some solutions are using the proxy like this
https://github.com/ljm625/unblock-china-apps
