### ISSUE TITLE
The Music Bot stays online no mater what I do 

### ISSUE THREAD

**Issue by BALVEY7** [Just-Some-Bots/MusicBot#2158]
Please tick all applicable boxes.

- [ ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

so I summon it and it goes offline then I summon again and it still goes offline and I tried update and else but it still didn't worked

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5461689/musicbot.log)

**Comment by Jcodeerd** [comment]
I started my bot, but there's and error!
 
__new__() got an unexpected keyword argument: 'deny_new'



If you are on windows, simply do py -m pip install -U discord.py[voice] and that should fix it.
If you are on linux or mac os, do pythonx.x -m pip install -U discord.py[voice] and replace x.x with your python version, for example python3.7 and your error should be gone aswell.

You can also change the requirements.txt file so that it looks like this: 
pynacl==1.4.0
discord.py[voice]==1.4.1
pip
youtube_dl
colorlog



Then run update.bat (If you're on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat (Same note as before). Please make sure to press n when asked if you'd like to reset files then y when asked if you'd still like to update dependencies.

**Comment by BALVEY7** [comment]
Okay that worked but when I want to make it do this
!play (and the link here)
it comes up with error  Unable to extract JS player URL

**Comment by Jcodeerd** [comment]
Restart your device

Op vr 30 okt. 2020 01:18 schreef BALVEY7 <notifications@github.com>:

**Comment by ph1n0** [comment]
I have the exact same issue, it seems to be youtube-dl related.
`[ERROR:bot] Error in play: CommandError: Error extracting info from search string, youtubedl returned no data. You may need to restart the bot if this continues to happen.
Traceback (most recent call last):
  File "/home/pi/MusicBot/musicbot/bot.py", line 2813, in on_message
    response = await handler(**handler_kwargs)
  File "/home/pi/MusicBot/musicbot/bot.py", line 1457, in cmd_play
    "You may need to restart the bot if this continues to happen."), expire_in=30
musicbot.exceptions.CommandError: Error extracting info from search string, youtubedl returned no data. You may need to restart the bot if this continues to happen.
`
