### ISSUE TITLE
[Feature request] Bot should server deafen self (if it has permission)

### ISSUE THREAD

**Issue by jogerj** [Just-Some-Bots/MusicBot#2189]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----
### Description of issue
Bot should "server deafen" itself if it has permission to do so. Not only it gives users peace of mind, it should reduce bandwidth the bot uses up.

Otherwise, a reminder advising server owners to server deafen their MusicBot is also a good idea.

**Comment by AutumnClove** [comment]
A couple of things, deafing it won't reduce bandwidth because no code is in place to listen, perhaps an option could be added, I know some people like the idea to make it more easy to immediately spot the bot, however personally I've never seen the point as server admins can just (usually) deafen the bot themselves which sticks around until someone removes it. 

I've also been a fan of not deafening it as many bots due because personally (and this is just my opinion) it makes it just a little more unique from other bots. I'll keep this open for now in case anyone wants to pr, or if I ever get around to it.

**Comment by AutumnClove** [comment]
Added in the review branch ask in the discord if you need help getting on the review branch
