### ISSUE TITLE
Dependency Conflict

### ISSUE THREAD

**Issue by myNameArnav** [Just-Some-Bots/MusicBot#2245]
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

When I run the command to install the requirements, it gives the following error: 
```
INFO: pip is looking at multiple versions of pynacl to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install discord-py[voice]==1.2.5 and pynacl==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pynacl==1.2.1
    discord-py[voice] 1.2.5 depends on PyNaCl==1.3.0; extra == "voice"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

### Steps to reproduce

1. run ```sudo python3 -m pip install --upgrade -r requirements.txt```

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Jcodeerd** [comment]
__**Change the requirements.txt file so that it looks like this:**__
```
pynacl
discord.py[voice]
pip
youtube_dl
colorlog
```

Then run update.bat(if your on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat(same note as before). Make to to press `n` and then `y` that way it doesn't reset the requirements.txt file back to the original.

__**Why do I need to change the requirements.txt file?**__
Discord pushed an update that broke discord.py, it was fixed in a new version of discord.py however we haven't updated the requirements.txt file on the master branch to target the latest version of discord.py with the fix.

__**PS:**__ Please do not edit the requirements.txt file with notepad as it can lead to format issues, instead use some sort of IDE, some popular options are; Sublime text 3, Microsoft Visual Studio, Eclipse, and PyCharm.

**Comment by AleanaA** [comment]
> 
> 
> ****Change the requirements.txt file so that it looks like this:****
> 
> ```
> pynacl
> discord.py[voice]
> pip
> youtube_dl
> colorlog
> ```
> 
> Then run update.bat(if your on windows, if not chose the appropriate update file for your system OS) once it's all up to date, then do run.bat(same note as before). Make to to press `n` and then `y` that way it doesn't reset the requirements.txt file back to the original.
> 
> ****Why do I need to change the requirements.txt file?****
> Discord pushed an update that broke discord.py, it was fixed in a new version of discord.py however we haven't updated the requirements.txt file on the master branch to target the latest version of discord.py with the fix.
> 
> ****PS:**** Please do not edit the requirements.txt file with notepad as it can lead to format issues, instead use some sort of IDE, some popular options are; Sublime text 3, Microsoft Visual Studio, Eclipse, and PyCharm.

Issue is resolved with this, or by using the review branch
