### ISSUE TITLE
Bot destroyed autoplaylist

### ISSUE THREAD

**Issue by shotty46290** [Just-Some-Bots/MusicBot#2281]
### What went wrong?

After having my auto playlist with about 300 songs going for months, today I got a bunch of errors that removed my whole auto playlist from 300 songs to a whopping 5 songs. I am attaching the removed auto playlist txt which has the errors. I will have to rebuild my list again from scratch, however I am afraid to spend that amount of time again for my whole playlist to be destroyed.

On a side not, is there any way to comment out sections of the auto playlist so I can organize and know what link is to what song? I spent a lot of time trying to make my list read-able and edit-able, but all my work was destroyed when the bot shoved them all into a line of their own

[autoplaylist_removed.txt](https://github.com/Just-Some-Bots/MusicBot/files/7734442/autoplaylist_removed.txt)
.

### How do we reproduce this?

no idea, worked for months for it to blast my whole autoplaylist

### Which version of the bot are you using?

release-260419

### Which operating system are you using?

Windows 7 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment]
The overall issue here is caused by Youtube-DL breaking.
The bot removes songs from the autoplaylist that it's unable to load, in this case, nearly every song off youtube errored, and were removed.

There are two things of note with this issue, one, the bot has since been updated to use yt-dlp rather than youtube-dl, as youtube-dl has gone inactive over, and yt-dlp resolves a number of issues, and second, the youtube links for each removed entry is just under each error listed.

In regards to organization, and this I'd recommend making a backup copy of the autoplaylist for the future as, while the removed list provides you the links, it will not preserve their spot in the file, lines preceeded by `#` will be ignored by the bot, allowing you to organize the file however you'd like.
