### ISSUE TITLE
Web pannel

### ISSUE THREAD

**Issue by HausCrafter8788** [Just-Some-Bots/MusicBot#2310]
### What new feature would you like to see?

Can you add an web dashbord to add another way to add songs in quere

LG HausCrafter8788
;D

### Which of these categories fit your request?

Other

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by BabyBoySnow** [comment]
I don't see this happening web dashboard would require a url/web domain, since the bot is self hosted it would be hard to create something like that without complications for the end user, and without the end user having to pay. MusicBot is free to use and we'd like to keep it that way. Many other musicbots on discord ask for payments for premium features, MusicBot is unique in the fact that it's self hosted, and free to use all the features.
