### ISSUE TITLE
[Feature Request] time and date based logging system

### ISSUE THREAD

**Issue by OzzyHelix** [Just-Some-Bots/MusicBot#2340]
### What new feature would you like to see?

I believe the current logging system could be better. Sure it works for what it does but using times and dates in the file names of the logs would be nice to have. I attempted to make a pr with my own fork to implement this but I lack the skill to do it correctly so I will not be making PR's anymore. another thought I had was deleting super old logs maybe logs older than 60 days but then again users may wish to go back into old logs to get songs links from the past. I welcome anyone with forks to try and make PRs for this and I hope this will make its way into the bot in some shape or form some time into the future

### Which of these categories fit your request?

Other

### Just checking...

- [X] I have confirmed that my feature has not already been requested.
- [X] I have confirmed that my feature has not already been implemented in the `review` branch.

**Comment by OzzyHelix** [comment]
wonderful this issue is resolved

**Comment by BabyBoySnow** [comment]
The dev branch has lots of exciting changes ;)

**Comment by OzzyHelix** [comment]
this is good there is just one thing that I would request the filename of the log files contain dates and time and a routine to clean up older log files I could add that to this issue or open a new issue might open a new issue?

**Comment by OzzyHelix** [comment]
I will make a new request for this

**Comment by itsTheFae** [comment]
Currently the file name is taken from the default log file names.   There are a few command line arguments you can use to enable the log rotation, and set a custom date-format for the date/time used in the file name.   
These options are only available via command line flags, but they should be added to config at some point too.   For now you can see them by using `python run.py --help` since they are currently only documented on the PR that merged them.

I should mention that log file rotation is only done at shutdown, so if you start the bot without the flags it will not rotate the log and the next run will overwrite it.

This probably wont be a perfect solution, as managing logs is usually better done with a dedicated tool, like logrotate for linux or something similar in windows land.

**Comment by OzzyHelix** [comment]
my biggest issue was the log overwriting itself again and again so I thought a system where the log files had the date in them and then there was a clean up routine would be a good route perhaps I am wrong

**Comment by OzzyHelix** [comment]
I didn't know about `python run.py  --logs-kept 100`
