### ISSUE TITLE
ShoutCast/IceCast Servers

### ISSUE THREAD

**Issue by thewillwilson** [Just-Some-Bots/MusicBot#264]
A way to stream of shoutcast and or icecast servers.

Would be amazing.

**Comment by imayhaveborkedit** [comment]
Streams aren't supported yet because the bot predownloads things before they're played, but I will add a way to play streaming media.

**Comment by Zaddion** [comment]
iHeart streaming would be cool too, but I don't believe it is possible.

**Comment by thewillwilson** [comment]
iHeart might be possible by using : http://developer.iheart.com/api/

**Comment by imayhaveborkedit** [comment]
The bot does not use any external API to resolve anything.  It uses youtube-dl.  If ytdl supports it, then it will probably work with the bot.  Consider requesting iheartradio support on the youtube-dl github page.  

That said, it's not impossible to use iheartradio.  I just tested this now.  You can pass the playlist link to the stream command and it'll play.  You have to find that link though.  I got mine by watching requests in ublock origin, but you can probably do the same thing with your browser's network inspector.

**Comment by Conobi** [comment]
I really hope that it will be added quickly. It would be so cool !

**Comment by jayktaylor** [comment]
Streaming is coming soon. It's already mostly if not completely implemented in `review`.

**Comment by deansheather** [comment]
Duplicate of #165. Going to close that issue, seeing as this one is in the milestone.

**Comment by ghost** [comment]
anything with this yet?

**Comment by chuushi** [comment]
Streaming works on the review branch of this project.  Switch to or download the review branch of this and try it out.

**Comment by jayktaylor** [comment]
The stream command is in the bot now.

**Comment by TiagoFrancisco2160424** [comment]
Hi, 

So which is the command? !stream url?
Because I have those Radio's IP's: 

HiperFM: http://85.25.73.243:10460/
RFM: https://playerservices.streamtheworld.com/api/livestream-redirect/RFMAAC_SC
Mega Hits: http://19553.live.streamtheworld.com:80/MEGA_HITS_SC
+Kizomba: http://109.71.41.250:8123/
Orbital: http://195.23.85.126:8401

In those radios url's, just the RFM Station works. "!stream https://playerservices.streamtheworld.com/api/livestream-redirect/RFMAAC_SC"

Regards.
