### ISSUE TITLE
No sounds after 2 hours of play ++

### ISSUE THREAD

**Issue by nandadytm** [Just-Some-Bots/MusicBot#276]
The titles describe it all, no sound after more than one or two hours or more, even if the bot say it play something. Running it on Ubuntu 14.04 and Windows 10. Same problem on both. The problem can be fixed after restarting the bot. Any workaround?

**Comment by NielsOkker** [comment]
I have the exact same problem. Running with windows 10 and windows server 2016. !restart is working indeed. It is not crashing, but just gets quiet.

**Comment by jayktaylor** [comment]
**Why does the audio stop after a while?**
Sometimes, usually because of Cloudflare restarting to apply updates, the websocket connection to Discord closes. This will result in the bot operating normally, but no audio being outputted.
If this happens, just run `!restart` (or `!disconnect` then `!summon`).
Alternatively, switching regions should fix it too.
It's not so much a problem with the bot, it's a problem with the library `discord.py`.

See also: #263

**Comment by imayhaveborkedit** [comment]
This should be fixed.

**Comment by tomvlk** [comment]
Still an issue for me. Also after updated lib.
