### ISSUE TITLE
Abit laggy

### ISSUE THREAD

**Issue by Sanjigen** [Just-Some-Bots/MusicBot#328]
When playing music there are momments of lag

**Comment by sideh** [comment]
I get this alot too but not sure what it is. 

Whether the server i'm using to run it is not is enough performance wise? Maybe bandwidth? or if it is a complicated process that just happens.

Looked at a few Bot's for discord on the carbon site, but this one still seems (from what I can tell) to be the best one for music.

Running off a AWS t2.micro instance with a vCPU at 2.4ghz and 1GB of RAM. Is this enough? or is there a service you would recommend to be better?

**Comment by Neclord9** [comment]
I have the same problem, I've run the bot on my own PC with a connection of 20up/20down and it still has these periodic instances of lag through every song from start to finish.

**Comment by Mrwebente** [comment]
me too. i don't think this is due to my pc or [bandwidth](http://www.speedtest.net/my-result/5394290061)

**Comment by junhui-f** [comment]
Might be this
https://www.reddit.com/r/discordapp/comments/4nebgy/poor_connection_to_singapore_server/

**Comment by arunesh90** [comment]
@Grift if you actually looked at the bandwidth link, then you would've seen that he lives in Germany, and not in Singapore.

**Comment by Neclord9** [comment]
If it helps at here are my speedtest results, Love the bot but i'm just curious of what is causing this <bR> <a href="http://www.speedtest.net/my-result/5396557399"><img src="http://www.speedtest.net/result/5396557399.png" /></a>

**Comment by brawaru** [comment]
You can try give more CPU to your bot by changing priority of process. This helps sometimes.

**Comment by sideh** [comment]
On my AWS server which is running the bot, it has never gone past 10% CPU usage.

**Comment by arunesh90** [comment]
If the audio stops after a while, it is usually because of Cloudflare disconnects. Discord uses Cloudflare so that DDoS attacks are mitigated, among other things. The bot should try to automatically reconnect within a minute.

Forcing reconnects - Change voice server, or !restart, or !disconnect and then !summon
Additional troubleshooting - Make sure you're using the latest version of the bot

If the audio is lagging, it can be down to a number of reasons. You should check each of the following for potential problems and issues.

CPU/disk usage - If the CPU/disk usage is high, it can lag out your bot.
Internet speed/bandwidth - If your internet isn't too great, it can lag out your bot.
Discord's servers - Discord sometimes has problems. Try switching voice server.

**Comment by jayktaylor** [comment]
Not our problem - this should be closed.
