### ISSUE TITLE
How to make the bot restart if crashes

### ISSUE THREAD

**Issue by edelin3** [Just-Some-Bots/MusicBot#353]
How was I make a .sh file where if the bot crashes it will restart even if I do !shutdown

**Comment by brawaru** [comment]
``` bash
while true
do
  ./run.sh
done
```

not?

**Comment by edelin3** [comment]
permission denied and I can't change the permissions file yet

**Comment by jaw3l** [comment]
`chmod +x run.sh` if u meant that

**Comment by exec** [comment]
I'm assuming you're using Linux. If not, it shouldn't be hard to emulate what I'm doing here.

Using screen and cron (hopefully you'd be using screen anyway, it's wonderful)
Add a new screen session command on the beginning of the last line of your run.sh file.

``` bash
screen -dmS musicbot python3.5 run.py # "dm" will start it detached, if that's your thing
```

(or something like that)

Then create another file wherever you want, let's say in your home dir, /home/user
This one will act as your watchdawg

``` bash
#!/bin/bash
SCREENS=$(screen -ls | grep musicbot | wc -l)
if [[ $SCREENS -eq 1 ]]; then
    echo "it's raining normally"
elif [[ $SCREENS -lt 1 ]]; then
    echo "it's raining sideways!!1"
    cd /path/to/musicbot/
    screen -dmS musicbot bash python3.5 run.py
else
    echo "too much screen bow-wow raining upside-down"
    echo "(but i don't get paid enough to do anything about it)"
fi
```

(or something like that)
and put it in your /etc/crontab to execute every... say... 10 minutes...? Really up to you

I'm not completely sure if that code'll work since I haven't tested it and I'm too inebriated to test it at the moment, but it should give you an idea of what to do. Hoping it helps.

**Comment by jayktaylor** [comment]
**PEBKAC.** If you read the guide, this information is available there: https://github.com/SexualRhinoceros/MusicBot/wiki/Installation-guide-for-Ubuntu-14.04-and-other-versions#3b-start-the-bot-permanent

**Comment by danfinlay** [comment]
Yes, this issue could be closed. Edelin was just learning about file permissions.
