### ISSUE TITLE
Bot crashes when connection to discord is lost

### ISSUE THREAD

**Issue by gryphus1153** [Just-Some-Bots/MusicBot#41]
Whenever I lose internet connection or discord server crashes the bot crashes.

**Comment by deansheather** [comment]
Discord server crashes?? Wha? :joy:

**Comment by gryphus1153** [comment]
The Singapore Discord cluster has been crashing or um, losing connection since yesterday

**Comment by deansheather** [comment]
10/10 Discord.

About the bot, as soon as it loses connection the socket dies out. That would mean the bot would have to stay open and try to connect every couple of minutes to achieve this functionality that you want. Most people would rather have the bot completely die rather than stay open and constantly try to reconnect.

If you're having Discord server problems, check the [Discord status page](https://status.discordapp.com/) for more information (I looked and I see nothing). If you're repeatedly seeing the same issue, contact Discord.

**Comment by gryphus1153** [comment]
I don't see anything about it either. But it seemed to affect all users on different servers on the SG cluster. 

Anyways, Is there any planned functionality to change this as a config or a script I could create to restart the bot automatically after 5 mins or something?

**Comment by deansheather** [comment]
You could definitely make a script to restart the bot every time it crashes or something. There are plenty of [articles on the internet](https://www.raymond.cc/blog/keep-application-running-by-automatically-rerun-when-closed/) (that's for Windows, I assume you're running Windows like most people do) that will help you restart the bot when it closes.

**Comment by srhinos** [comment]
As was said by dean, simply edit the bot's batch script to restart whenever it crashes and it'll work fine

**Comment by ThePhilosopherV** [comment]
i had same issue and i fixed it using this method :+1: 
i edited \Python\Python36-32\Lib\site-packages\aiohttp\connector.py  as you see in the image;i made 
transport, proto = \
yield from self._create_connection(req) 
in a try except statement (in my case my bot will exit when ever my internet connection is lost)
![screenshot at 2018-08-27 09-40-42](https://user-images.githubusercontent.com/42734412/44650216-e6cf1e00-a9dd-11e8-99e1-2eeb98eb7d55.png)
