### ISSUE TITLE
Skip to part in song

### ISSUE THREAD

**Issue by LouieK22** [Just-Some-Bots/MusicBot#452]
Can we have an option to skip to a part in a song. Like !skip 1:23 for the song. Would be nice to skip stuff before a song or point out a certain point in a song to a friend.

**Comment by siku2** [comment]
**Edited on 20/02/2017 at 17:05**

Since a long time has passed since this has been requested and it hasn't been implemented yet, these are the necessary changes you need to make to have it right now:

The forked Github repository is [here](https://github.com/siku2/MusicBot-Request-Fulfillment/tree/skipto)

And here's the commit:
dfcbac078deac4753618a430fda3a68b72d03a4b

**Here's the commit for forward and rewind functions**
43b8d13e212e86688312b281ab8f0085e1be6327

Feel free to hit me up over at Discord (**siku2#7390**) if there are any questions.

**Comment by jayktaylor** [comment]
@siku2 To help people further it'd be good if you had this in a fork or as a pull request so people could see the changes you've actually made.

**Comment by siku2** [comment]
@jaydenkieran Thanks for the tip! I will do that as soon as I'm at home

**Comment by siku2** [comment]
@jaydenkieran Something like [this](https://github.com/siku2/MusicBot-for-LouieK22)?

**Comment by jayktaylor** [comment]
@siku2 That's helpful and a lot easier to read now, thank you 👍

**Comment by TheLegend27NL** [comment]
I don't believe this works anymore, I've tried but sadly can't get it to work anyways. I still have absolutely zero experience with python, can anybody help? I really need this command, I'd use it more than play.

**Comment by amit177** [comment]
An implementation could be something like this:
Figure out a conversion rate between frame count and minutes in the track, kill the current player and start reading from that frame.

Let me know what you guys think.
@AleanaA @AutumnClove @TheerapakG
