### ISSUE TITLE
Bound to text channel/Role Permissions

### ISSUE THREAD

**Issue by RoboAwsome** [Just-Some-Bots/MusicBot#518]
I've done what it said for it to do for the text channel and for roles to use the commands but neither are working

**Comment by jayktaylor** [comment]
Please read https://github.com/SexualRhinoceros/MusicBot/wiki/Configuration-file for more information on configuring the bot.

For permissions -

:key: How to setup **Permissions**
**To start:** Open `permissions.ini` in the config folder (read the top of the file for information)

:memo: **Whitelisting a command:**
**-** To allow a user to use a command, add it in the `CommandWhitelist` section
**-** If the `[Default]` group has a command in that section, **anybody** can use that command
:person_with_blond_hair: **Add a user to a group:** (https://goo.gl/cAZBMa)
**-** To add a user to a group, put their ID in the `UserList` section
**-** To find out how to get a user's ID, type `!tag ids` here
:flags: **Add a role to a group:** (https://goo.gl/7ujPG9)
**-** To add a role to a group, put that group's ID in the `GrantToRoles` section
**-** To find out how to get a role's ID, type `!tag ids` here

**NOTE:** When you add a User/Role to a line that is commented (has a `;` at the beginning), remove the semicolon, otherwise the bot won't detect your changes.
