### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by barringtome18** [Just-Some-Bots/MusicBot#523]
So i have been trying to get permissions to work yet after everything ive done i still cannot ristrict access to users ill show the code, if someone could help me that would be fantatic
![capture](https://cloud.githubusercontent.com/assets/21177335/17860670/33f56f74-685c-11e6-8b6d-a1df32ce2168.PNG)

as you see i have the user's id who i want to ristrict from the bot yet the user in question can still use !play

**Comment by jayktaylor** [comment]
:key: How to setup **Permissions**
**To start:** Open `permissions.ini` in the config folder (read the top of the file for information)

:memo: **Whitelisting a command:**
**-** To allow a user to use a command, add it in the `CommandWhitelist` section
**-** If the `[Default]` group has a command in that section, **anybody** can use that command
:person_with_blond_hair: **Add a user to a group:** (https://goo.gl/cAZBMa)
**-** To add a user to a group, put their ID in the `UserList` section
**-** To find out how to get a user's ID, type `!tag ids` here
:flags: **Add a role to a group:** (https://goo.gl/7ujPG9)
**-** To add a role to a group, put that group's ID in the `GrantToRoles` section
**-** To find out how to get a role's ID, type `!tag ids` here

**NOTE:** When you add a User/Role to a line that is commented (has a `;` at the beginning), remove the semicolon, otherwise the bot won't detect your changes.

**Comment by barringtome18** [comment]
there is no user list section under limited, do i add one or make a new "limited" group for users?

**Comment by jayktaylor** [comment]
The information at the top of `permissions.ini` explains how to configure permissions properly. If you need more help, join our help server. https://discord.gg/eCcFqvm
