### ISSUE TITLE
Twitch chat / IRC chat support

### ISSUE THREAD

**Issue by OrdinatorStouff** [Just-Some-Bots/MusicBot#620]
I would love to see support added for the bot to join and listen on a Twitch.tv chat channel (or an IRC-based chat channel for that matter) to accept and respond to commands.

For starters, bot permissions/groups would need to be taken into consideration on how to implement cross-medium. Perhaps the IRC functionality can be 'listener-only' and have a special bot permission group?

**Comment by ImthePeach** [comment]
Twitch chat integration most likely won't be offered. I have asked Imayhaveborkedit before but it doesn't sound like he is going to want to do this and the integration with Twitch would be a nightmare and a half to do.

**Comment by deansheather** [comment]
Twitch is IRC, and IRC isn't super hard to make a bot for. Someone with some basic scripting/coding knowledge could create a bot/webhook that forwards messages from IRC into a Discord channel.

This is not practical, though, as permissions would not carry through. This is impractical for the entire bot to include this functionality, as no one will use this functionality and permissions changes will be hard to implement in order to support Twitch users.

Why not just ask the users to join your Discord server to request tracks?
