### ISSUE TITLE
Decrasing the amount of space?

### ISSUE THREAD

**Issue by SecundusLullaby** [Just-Some-Bots/MusicBot#639]
Since the day I created the bot it strangely lowered the empty space in my C: day by day but saving video option is off. Any suggestions what else could be doing this?

**Comment by junhui-f** [comment]
Have you checked if the folder containing the bot is even the problem? Screenshot the folder properties so we can see what is going on ...

**Comment by CGUANGJUN** [comment]
Same here, I always delete the audio_cache after i stop using the bot but still my amount of space doesn't goes back to original instead lower than the original ones. I found out this is quite a worry for me because i doesn't have much space left in my laptop and hope to solve this problem as soon as possible! 

https://gyazo.com/5321840ecf71475c430b95e79095657f <------ Screenshot of the folder
https://gyazo.com/5fff09df914980144c65df604708d135 <------- Screenshot of MusicBot Propertise?

**Comment by ElectronicWar** [comment]
Use something like [Scanner2](http://www.steffengerlach.de/freeware/scn2.zip) to find space hogs
