### ISSUE TITLE
You don't have permission to use that command.

### ISSUE THREAD

**Issue by jhuberus** [Just-Some-Bots/MusicBot#704]
Ok so let me explain. I have a pretty big discord server so we are running multiple bots with different commands. one with ! and the other one with *. However a problem occurs with the second bot that is using * that whenever someone does !play in a different channel the other bot responds with (You don't have permission to use that command.) is there a work around for this

**Comment by CX13BVA** [comment]
This happens when someone use the !play command, but he isn't in a voice channel.
this can also happen when the user who used the command joined another voice channe before he send the command
You also should check permissions.ini, maybe you changed one of these `[Groups]` (never change the group name)

If you checked these points and the problem is still there, save your autoplaylist.txt & reinstall the music bot.

**Comment by jhuberus** [comment]
Looks like i fixed the issue, I somehow manage to run three instances of the bot. One of which was using the old command. After restarting my server it managed to fix itself and no longer interferes.
