### ISSUE TITLE
Allow Selection of Audio Quality

### ISSUE THREAD

**Issue by BNolet** [Just-Some-Bots/MusicBot#740]
Currently, you cannot select the audio quality that you want to be played. 

For Youtube specifically, I've found that converting the video to an embed link and adding ?vq=medium at the end fixes the issue. 

ex:
https://www.youtube.com/watch?v=oPpInGffxgM
becomes
https://www.youtube.com/embed/oPpInGffxgM?vq=medium

**Comment by arunesh90** [comment]
The bot always uses the highest quality. I don't see what's really wrong with that.

**Comment by BNolet** [comment]
It's a problem where either resources(low hardware specs) or connectivity(low internet speed) is limited. Not all of us are graced with octacore, 12GB, 30MPBS full duplex connections 😂

**Comment by Kedakai** [comment]
A Song that is about 180 seconds long and 20MB big needs an upload rate of nearly 900kbit/s.
But 20MB is really big for a youtube song.
I checked it right now with a Song that's 3:11 long and was uploaded with an FULL-HD video.

> [alexander@localhost:~] youtube-dl -F https://www.youtube.com/watch?v=T-GMow_2fIA
> [youtube] T-GMow_2fIA: Downloading webpage
> [youtube] T-GMow_2fIA: Downloading video info webpage
> [youtube] T-GMow_2fIA: Extracting video information
> [youtube] T-GMow_2fIA: Downloading MPD manifest
> [info] Available formats for T-GMow_2fIA:
> format code  extension  resolution note
> 249          webm       audio only DASH audio   58k , opus @ 50k (48000Hz), 1.23MiB
> 250          webm       audio only DASH audio   82k , opus @ 70k (48000Hz), 1.67MiB
> 140          m4a        audio only DASH audio  128k , m4a_dash container, mp4a.40.2@128k (44100Hz), 2.88MiB
> 171          webm       audio only DASH audio  136k , vorbis@128k (44100Hz), 2.83MiB
> 251          webm       audio only DASH audio  157k , opus @160k (48000Hz), 3.23MiB`

For the best quality here you need about 170kbit/s. I don't think that shouldn't be the problem for nearly 99% of the people out there. Even in the very little Village we had about 3.29Mbit/s Download and 672kbit/s Upload. 
A thing that i didn't calculate was, that if you speak as well. That causes the upload traffic to double. But this shoudln't be a problem as well.
And (honestly) i don't think you will have fun with opus @ 70 or @ 50. 

I just checked it on my server with nload.
And as i said earlier, its not more than 170Kbit/s. In fact, the peak was at 156,54kbit/s. avg was below 150Kbit/s.

**Comment by BNolet** [comment]
The problem in my case was not the network connectivity but rather the resources available to the machine. I don't know what the resources for this specific machine I was working with was (Was running on a community member's VPS) but songs that had an available resolution of something like 720p or higher would stutter, and stutter hard. 

It's really just a feature request, not a bug so it's not extremely important, I'm just saying there are cases where it would be necessary.

**Comment by MattBSG** [comment]
The bot downloads the song files through YouTube. It then streams them through discord at the highest bitrate possible in discord regardless of channel setting. This is an issue with your VPS's internet connection. Try changing your voice region.

**Comment by Kedakai** [comment]
@MattBSG , it could be another problem though.
If you have VPS Servers with shared cores (Which the companies call "vCores" or "virtual Cores") some providers put too much machines on a single Hypervisor. 
Example:
If a Hypervisor has 4 Cores and 8 Threads, Linux should'nt have a load over 7.80 (0.20 for System Operations reserved). 
Now, if a bunch of people (Lets say 8 out of 30 ) starts to "create" some cpu load. 
Then the Server takes all 8 "Cores" and schedule "cputime" for each VPS.
When a server is overloaded then all VPS will get very very slow.
"apt-get install vim" for examples took 30 Minutes in my case!

My suggestion is, that ffmpeg is not able to process the amount of data coming from the Soundfile. That means it cannot process the file "live". Stutter begins.
I suggest this because i own several hypervisors in germany and experienced that problem before.

**Comment by MattBSG** [comment]
Yes, that is true. I was mostly targeting the fact that he wanted to lower the bitrate. This is also the case. Also stated that he was using a shared VPS with another user, so this is more likely the issue

**Comment by sn8to** [comment]
@MattBSG (for two answers above)

Discord automatically moves users to voice regions for better clarity when their current voice region is bad or slower than another one as of a client update from a month or two ago.

**Comment by BNolet** [comment]
Discord is not the issue. 

The bot is not the issue. 

The issue is that when running the bot on a machine with super low resources, a lower bitrate is required.

I tested this by using a 1080p max available resolution source, having it stutter massively (unlistenable) and then using a Max 360p source and it working perfectly fine.

**Comment by Kedakai** [comment]
@BNolet , ffmpeg needs to have enought resources (CPU and disk mainly) to "convert" the song in real-time. A song with a higher bitrate needs, obviously, more CPU resources than a "low bitrate" Song.
BUT, that shouldn't be the issue. As a said before, only if the Provider wrecks something up or there are too many Clients on a hypervisor ffmpeg has to wait too long for CPU-resources given by (For example) KVM.
The Bot runs on a Raspberry so any pentium 4 should do it.
And again as i said, this is an provider Issue of your VPS, because they overload the Hypervisor in a way that is and will be never recommended.
I suggest that you rent s server at a new provider. 
https://www.hetzner.de/ot/hosting/produkte_vserver/cx10 should do a very good job.

**Comment by BNolet** [comment]
Ah so the issue _is_ hardware but moreso the unbalanced virtualization of it. 

Is implementing such a feature as originally mentioned something that would be difficult to implement?

**Comment by MattBSG** [comment]
I mean, no, but it seems pointless as it would drastically reduce the quality for users listening for little to no benefit (since downloading audio only anyway).

**Comment by Kedakai** [comment]
I agree with that.

This feature is something that's only useful if the server provider wrecks something up.
I mean, a Raspberry is enought for ffmpeg to convert in real-time.

So if a feature like this is needed, you should consider to get a new VPS from a new provider.
Everything else should work without any problems.
