### ISSUE TITLE
Soundcloud playback error.

### ISSUE THREAD

**Issue by laurencebrwn** [Just-Some-Bots/MusicBot#750]
Whenever requesting a new soundcloud song I get this error: 
`ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)`
Any help would be appreciated.
Thanks in advance.

**Comment by arunesh90** [comment]
If you are having issues playing music from certain websites such as soundcloud such as

[0;31mERROR:[0m Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by <HTTPError 401: 'Unauthorized'>)


Resolution/Fix:

On Windows run update_deps.bat
On Mac run update_macdeps.command
On Linux run sudo pip install --upgrade youtube-dl
