### ISSUE TITLE
Music bot lagging BAD

### ISSUE THREAD

**Issue by koolTREVV** [Just-Some-Bots/MusicBot#769]
Music bot is behind a firewall 
Every few seconds it just cuts out for a split second and some times slows down and speeds up
(Im not too good with this stuff 😢 well a tiny bit but yeah)

**Comment by MattBSG** [comment]
Check your system resources, it's most likely CPU

**Comment by CalebBarnes2** [comment]
lagging for me CPU is at 40% WITH a game running

**Comment by KingGold171** [comment]
audio: :microphone: If your bot cannot play music
- Check if it is muted/server muted
- Try changing voice region
- Check that the issue is being caused by the bot, not you or the server
- Check for errors in the console
- Try !restart to restart the bot or !disconnect and then summon to reconnect the bot
:microphone: If your bot is lagging when playing music
- Check CPU/disk usage
- Can your PC/the VPS' bandwidth/speed handle the bot?
- Is there an issue on https://status.discordapp.com?

**Comment by Kedakai** [comment]
@koolTREVV , @calebbarnes , in linux you can print disk-io-usage with the command "iotop" in Windows it something like "System resources" (i don't know exactly because i'm not using windows).
This issue is called "I/O Wait" or "CPU Wait", because CPU has to wait for drive to execute the "stuff".

**Comment by Luminary-Five** [comment]
I would like you to run this and then tell me what the resaults are form it most likely its your internet speeds being shit
[http://beta.speedtest.net/](url)
