### ISSUE TITLE
[Question] What has better stability - API or Account?

### ISSUE THREAD

**Issue by ghost** [Just-Some-Bots/MusicBot#776]
Hi! We're using 4-6 bots on different Discords.  We've chose to make separate accounts for these bots.

Now, these accounts like to disconnect from the channels, making it very frustrating for some of our members that's want to use these bots at random times. A moderator with permissions have to !restart each time these bots drop, and it happens a lot.

Would switching to the API option fix this, or is there something else going on? We have a pretty beefy OVH server so I don't think CPU or hardware is the problem.

**Comment by jayktaylor** [comment]
Using an [official bot account](https://github.com/Just-Some-Bots/MusicBot/wiki/FAQ#how-do-i-create-a-bot-account) will always be better. Most of the issues such as random disconnects however are caused by Discord themselves (or Cloudflare, considering they utilise their services). Try using bot accounts, as well as the `review` version of the bot.

The `review` branch features additional reconnect logic that may prevent the bot from going offline as often as it currently is. To switch to this version instead, use the command `git checkout review` inside your bot folder(s). 

Please note that we don't provide much support for the `review` version of the bot as it is the "cutting edge" and "actively developed" version of the bot. There could be other bugs we're unaware of.

**Comment by ghost** [comment]
```
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:265> exception=ConnectionClosed('WebSocket connection is closed: code = 4015, reason = Voice server crashed..',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 614, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 298, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 272, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 617, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed..
262247111490404354/dj-sona#0871 has joined 🔥 GhostFire Gaming/Game & Chill  🎧 🔥
Connected to 🔥 GhostFire Gaming/Game & Chill  🎧 🔥
```

**Comment by jayktaylor** [comment]
`discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed`

It isn't our issue, Discord's voice server crashed.

**Comment by dannymichel** [comment]
So is there any way to make it so the bot restarts and rejoins automatically after the voice server crashes?
