### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by RheaAyase** [Just-Some-Bots/MusicBot#847]
Really guys, it's useful and not `cancer`, as many have said in #666 (that number huh)

https://help.github.com/articles/setting-guidelines-for-repository-contributors

**Comment by arunesh90** [comment]
We've already explained it in detail in your issue.

**Comment by RheaAyase** [comment]
And I still can't see the `CONTRIBUTING.md` file. 

Examples:
[dotnet](https://github.com/dotnet/corefx/blob/master/CONTRIBUTING.md)
[mono](https://github.com/mono/mono/blob/master/CONTRIBUTING.md)
[rails](https://github.com/rails/rails/blob/master/CONTRIBUTING.md)

Guys, nearly every serious project has some guidelines.

**Comment by ImthePeach** [comment]
**HOW TO CONTRIBUTIONS:**

Step 1) Fork the repository
Step 2) Do what you wish in your fork
Step 3) Submit a pull request (To the Review Branch, we will only look at these because review branch is under development and we won't push to a stable branch in case things break)
Step 4) wait
Step 5) wait some more

Result: We will either decide to maybe use it, or will deny the Pull Requests.

Note: for the most part, pull requests of this MusicBot are just 'fancy feature requests'.

**Comment by jayktaylor** [comment]
Hello Rhea. We have discussed this internally and will look into adding contribution guidelines to `CONTRIBUTING.md` in the future, however we don't plan to do this right now. We're not updating MusicBot's repository until [discord.py's rewrite](https://github.com/Rapptz/discord.py/tree/rewrite) is officially released and complete, and that includes what you're requesting in this issue. I'm going to keep this issue open and unlocked for discussion for now. 

To those reading this before any repo changes are made:

- The base branch for pull requests should be **review**. That is our development branch. We ask you to set this as your base because it will have more features and changes than the latest official bot release, and your PR feature or bug fix may already have been implemented. 
- Bug-related PRs should ideally reference an issue, or describe an issue with steps to reproduce.
- Feature-related PRs should make sure not to use blocking code and utilise `asyncio`. Features should not be generic to a bot, such as a command to broadcast to all servers. If it isn't related to music, don't add it. Make your own fork and maintain that instead. 
- We have a page on our wiki for [modification](https://github.com/Just-Some-Bots/MusicBot/wiki/Modification). If you're going to add or change commands, please ensure you have read this page as it contains information about our current command framework. This is subject to change in the future, however. 
- We **do not** accept 'cosmetic' PRs. This includes reformatting code to adhere to Python's PEP8 guidelines.

**Comment by jayktaylor** [comment]
Initial contribution guidelines, and templates for issues and pull requests were added as of tag 1.9.6_1. They may be expanded on in the future.
