### ISSUE TITLE
MusicBot with Pihole

### ISSUE THREAD

**Issue by Girtablulu** [Just-Some-Bots/MusicBot#854]
When I'm using the Bot in combination with Pi-hole and I'm blocking youtube ads, the bot throws a Error when the ad video is blocked and does not continue downloading, if the ad doesn't get blocked it's not a problem, is there anyway to get the bot continue downloading even the ad video gets blocked?

**Comment by ImthePeach** [comment]
Uh, did you modify our bot? The music bot doesn't download and play ads by default...

**Comment by Girtablulu** [comment]
no totally not, I have pihole and the Musicbot running on my Pi3, all DNS request on my LAN are running over pihole. 

When the Musicbot is opening the next youtube link and starts to download, I can see inside my pihole log that a ads link gets opened as well and pihole is going to block the ads video and let the normal youtube url pass but somehow the Musicbot doesn't like this and starts kicking out an error, which is saying that the the URL doesn't exists and deletes it from my autoplaylist :/

Could it be that the Musicbot still sees the ads link but tends to ignore it? But due the fact my DNS blocker blocks that URL, the Musicbot says well ads isn't playing so the youtube link isn't working as well.

I stopped blocking youtube ads and the bot is running without a problem

**Comment by ImthePeach** [comment]
The bot functions by downloading the video into an mp3 format. It does that without downloading any type of adds, because of the way ffmpeg and ytdl handle things. If you're pihole is interfering with the bot's processes then you will have to change it on your end. We won't be altering the bot to work around certain applications like pihole any time soon.

Seeing as how you got it to work again by stopping youtube ads from being  blocked I am going to close this issue.
