### ISSUE TITLE
[Question] Bot Playing?

### ISSUE THREAD

**Issue by student-alice** [Just-Some-Bots/MusicBot#888]
Hi there,
Just a question for developers: Is there any way to change what game the Bot is playing? I know it usually says the bot is playing whatever song is playing, but I am wondering if there is a way to customize this. Thanks for the help!

**Comment by junhui-f** [comment]
Looking at the source code in `bot.py`

```python
261        if entry:
262            prefix = u'\u275A\u275A ' if is_paused else ''
263
264            name = u'{}{}'.format(prefix, entry.title)[:128]
265            game = discord.Game(name=name)
266
267        await self.change_status(game)
```

**Comment by KingGold171** [comment]
You won't normally get help modifying the bot but all im do is post one of the fun facts about change_status
```
DeprecationWarning: change_status is deprecated, use change_presence instead.
  await self.change_status(game)
```

**Comment by OugiFormula** [comment]
its on the update_playing_now?

**Comment by jayktaylor** [comment]
Use this function: http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.change_presence

If you want to permanently have your own status rather than one that the bot sets, I'd advise removing or commenting out every mention of `update_now_playing` in the bot's code (`bot.py` etc).

Further modification info is here but may not be relevant: https://github.com/Just-Some-Bots/MusicBot/wiki/Modification

If you need more help with using the functions of `discord.py`, join http://discord.gg/discord-api.
