### ISSUE TITLE
Error installing Pip on Raspbian

### ISSUE THREAD

**Issue by caseydulong** [Just-Some-Bots/MusicBot#960]
I am on a Raspberry Pi 3 B with a fresh image of Raspbian Jessie.  I get an error while trying to install Pip.  I have followed all prior instructions in the Raspbian installation guide and received no errors.  When I run the command `sudo python3.5 get-pip.py` I receive the following error:

> pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

> Collecting pip
> Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping

> Could not find a version that satisfies the requirement pip (from versions: ) No matching distribution found for pip

**Comment by jaspersmitNL** [comment]
mm Im having issues aswell to compile..

**Comment by BraydonG** [comment]
Have you done

`sudo apt-get update
sudo apt-get upgrade `
to ensure all packages are up to date?

There is another command that might help but it would be nice to know if your are running it on a Raspberry Pi a what model.

**Comment by BraydonG** [comment]
Also do remeber when using the `make` command you can type `sudo make -j4` which will use your pi 3 quad core processor fully and speed up processes significantly.

**Comment by FIERCEDINO080** [comment]
having the same problem...

**Comment by Argos-Rho** [comment]
@FIERCEDINO080 Try my proposed solution.

**Comment by ShafiqAiman94** [comment]
sudo apt-get install python3-pip

try this,it worked for me..

**Comment by daocha** [comment]
I tried install libssl-dev openssl 

and python3-pip,

nothing works for me . 

It's still the same issue.

**Comment by GeoZzNL** [comment]
Reposting my own comment. Pip just dont work on a pi using python 3.5

I also had al lot of issues on my pi3.
Download Python-3.6.1.tar.xz from https://www.python.org/

Unzip the file and keep the folder in home directory.

Open terminal in that directory and perform the following commands:
./configure
make
make test
sudo make install
This will install Python 3.6 but pip3 may not be working.Install necessary modules using:
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

Now write the following to re run the installation (EDIT: USE -j4 FOR ALL CORES, WHICH IS ACTUALLY JUST 50% CPU):
sudo make
sudo make install

Now this, even if its again... (If pip3 is not working try pip)
sudo pip3 install numpy
sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

If not working, do not uninstall a thing but follow the ubuntu 16 guide.

Then try some of my codes again.

I do not have a really good guide because i tried installing the bot and it tooks more than 3 days. Some of these codes fixed it for me. Running 3 bots using python3.6

**Comment by WernerMauss** [comment]
I had the same issue as reported by caseydulong. 
I was following Argos-Rho's instructions but it did not solve the problem. 
Next I deinstalled python 3.6.0 from my RPi with Wheezy OS (Linux raspberrypi 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux). 
I followed GeoZzNL's steps to the first sudo make install. 
Thereafter, the issue was gone and I could do the intended installation using "sudo pip3 install virtualenv". 

Thank you very much for these hints, I would have had NO chance to solve that myself. 

Greetings
Werner
